name: Run Tests

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  run-eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version-file: package.json
      - run: npm ci
      - run: npm test
